### ISSUE TITLE
Provided Flow in Repository does not work with latest IE Flow Creator Version

### ISSUE THREAD

**Issue by Boehmi-TB** [industrial-edge/Developer-Guide-Hands-on-App#16]
# Issue-template

## Summary

Provided Flow in Repository does not work with latest IE Flow Creator Version
https://github.com/industrial-edge/Developer-Guide-Hands-on-App/blob/main/src/solution/IE%20Flow%20Creator%20Flows/flow_data_gen.json
When importing flow in function you get following error message
![image002 (1)](https://user-images.githubusercontent.com/74045802/209649221-ad40a4ca-1855-4f03-a9e8-476ef76ef9bf.png)
to fix error variable must be declared
![image003 (1)](https://user-images.githubusercontent.com/74045802/209649217-c017e056-5b33-401f-900c-33b6a4e0bae3.png)

## Version of the used components

- IE Flow Creator: V1.10.0

**Comment by EndyCZ** [comment]
Should be fixed by #14
