### ISSUE TITLE
Databus service name

### ISSUE THREAD

**Issue by chohensinn** [industrial-edge/Developer-Guide-Hands-on-App#9]
Databus service container name is still "ie_databus" this imho deprecated.

**Comment by HummelN7872** [comment]
Thanks for the feedback, where exactly did you found the legacy databus service name, could you please provide the section/ link.

**Comment by chohensinn** [comment]
My fault, I forgot to mention, where... 

https://github.com/industrial-edge/Developer-Guide-Hands-on-App/blob/3d8c1bced13c486ddf80bbd926145b75d2ba84a2/src/solution/mqtt_broker_mosquitto/docker-compose.yml#L11

I think this should be "ie-databus " otherwise the connection to mqtt service fails somwhere here: 

https://github.com/industrial-edge/Developer-Guide-Hands-on-App/blob/3d8c1bced13c486ddf80bbd926145b75d2ba84a2/src/solution/my_edge_app/data-analytics/program/data_analytics.py#L123
